# this file contains all the packages and dependencies required for making the snakemakeCS50 environment.
# https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#integrated-package-management

channels:
- conda-forge
- bioconda
dependencies:
# snakemake package
- snakemake-minimal >=8.4.4
# install python
- python
- jinja2
# include pip to install dependencies
- pip
- pip:
  - pysam
  - pandas
  - colorama
  - flask
  - pygments
# alignment and DNA mutation calling tools
- bcftools =1.19
- samtools =1.19.2
- bwa =0.7.17
